server:
  port: 9090
  servlet:    context-path: /banking-app

spring: 
   datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project
    username: root
    password: Paddumalli@123